name: "Fedora 36 Image"

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - 'Fedora-36/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'Fedora-36/**'

jobs:
  Build_Image:
    uses: ./.github/workflows/build-image.yaml
    with:
      name: "Fedora-36"
